name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/henrysi1va/light-100-firmware-zephyr:latest
      credential:
        username: henrySi1va
        password: ${{ secrets.GHCR_PAT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: west build -b qemu_cortex_m3 workspace/app
